### ISSUE TITLE
QGIS 2.0 Compatibility

### ISSUE THREAD

**Issue by spilth** [p0cisk/Generalizer#1]
This plugin doesn't seem to be compatible with or listed in the QGIS plugin list. Any plans to update it?

**Comment by p0cisk** [comment]
Hi
For now I don't have plans for updating Generalizer to QGIS 2.0. You can use v.generalize from processing toolbar instead.
Some time ago I've done some coding to incorporate this functionality as native SEXTANTE algorithm but this was before API changes. Maybe I will return to this when I will have some time.
